# Site settings
title: Design System Web
author: DÃ©partement de Loire Atlantique
email: contact@loire-atlantique.fr
url: "https://design.loire-atlantique.fr/"

# Build settings
destination: ../dist
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-minifier
sass:
  style: compressed

# Setup pattern collection
collections:
  variations:
    output: true
  posts:
    output: true
    permalink: /post/:year/:month/:day/:title/

# Configure minification
jekyll-minifier:
  exclude: ['*.html', '*.xml', '*.txt']  # Exclude xml and html files from processing (take too long to generate)

# Overriding default colors
branding:
  logo_path: 'https://www.loire-atlantique.fr/upload/docs/image/png/2013-11/entete-logo2.png'
  navigation_background_color: '#eee'
  navigation_link_color: '#444'
  navigation_link_color_hover: 'gray'
  main_background_color: '#fff'
  highlight_color: '#444'
  code_background_color: '#f9f9f9'

# Do not delete or change any file of the design system 
keep_files: [js, fonts, css, images]
exclude: [js, fonts, css, images]

# GTM analytics
gtm_id: UA-46270573-1
